### ISSUE TITLE
Unable to access Planka WebUI

### ISSUE THREAD

**Issue by Semias83** [linuxserver/docker-planka#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm unable to access Planka WebUI via URL or Local IP:port
Tables migration and migration_lock created in DB after 1st run of Planka

### Steps To Reproduce

1. Postgresql installed, database created, accessible via adminer.
2. Installation of Planka via Unraid Apps with this config:
-WebUI: 1337
-BASE_URL: https://taskmanager.mydomainname.xxx
-DATABASE_URL: postgresql://mydbusername:mydbpassword@192.168.0.1:5432/planka (password does not contain special characters)
SECRET_KEY: mysecretkey
TRUST_PROXY: 1

### Environment

```markdown
- OS: Unraid 6.12.13
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='planka'
  --net='revproxynet'
  --pids-limit 2048
  -e TZ="Europe/Paris"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="STUDIO-H-SERVER"
  -e HOST_CONTAINERNAME="planka"
  -e 'BASE_URL'='https://taskmanager.mydomainname.xxx'
  -e 'DATABASE_URL'='postgresql://mydbusername:mydbpassword@192.168.0.1:5432/planka'
  -e 'SECRET_KEY'='mysecretkey'
  -e 'TRUST_PROXY'='1'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/planka-logo.png'
  -p '1337:1337/tcp'
  -v '/mnt/user/appdata/planka':'/config':'rw' 'lscr.io/linuxserver/planka'

d045e5c90ca82e4345ed2dc832d2f1ee1a7c070eed41908669df2cd792cbf6cd
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
planka: https://github.com/sponsors/meltyshev

To support LSIO projects visit:
/etc/s6-overlay/s6-rc.d/init-planka-config/run: line 28:   143 Illegal instruction     s6-setuidgid abc node db/init.js
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────
Linuxserver.io version: v1.21.1-ls2
Build-date: 2024-09-12T18:26:31+00:00
───────────────────────────────────────
    
Waiting for DB 192.168.0.1 to become available on port 5432...
[custom-init] No custom files found, skipping...
```

**Comment by thespad** [comment]
Well the likely cause seems pretty clear:
```
/etc/s6-overlay/s6-rc.d/init-planka-config/run: line 28:   143 Illegal instruction     s6-setuidgid abc node db/init.js
```
But I have no idea *why* you're getting that error or indeed why there as that section of the init runs *after* the DB ready check.

Can you try running without any value for the DATABASE_URL and see if you get the same error?

**Comment by Semias83** [comment]
I tried with default values in DATABASE_URL and the error as gone. I just have a connection to DB error which is normal. As soon as I write my datas in DATABASE_URL, the error appears.

After investigating, Error appears when I type 192.168.0.1 (the adress of my server) in DATABASE_URL after the @
If I let text or the internal docker adress of my Postgresql docker (172.17.0.6), this error disapears. I have instead another error with DB connection.

The network type change sometimes the error. In bridge I can type 172.17.0.6, the error don't appear, just a connection error.
In my reverse proxy network, any of 172.17.0.6 or 192.168.0.1 make the error appear.

**Comment by thespad** [comment]
I've tried a bunch of combinations of IPs and hostnames for the database host but I still can't replicate the issue - you really should be using the internal docker bridge dns name anyway and not connecting by IP address.

**Comment by Semias83** [comment]
I tried by typing the name of my postgresql container (is it the internal dns name ?), I have a connection error:



[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
planka: https://github.com/sponsors/meltyshev

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────
Linuxserver.io version: v1.21.1-ls2
Build-date: 2024-09-12T18:26:31+00:00
───────────────────────────────────────
    
Waiting for DB postgresql16 to become available on port 5432...
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: getaddrinfo ENOTFOUND postgresql16
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'postgresql16'
}

Node.js v20.15.1
[custom-init] No custom files found, skipping...

**Comment by thespad** [comment]
Is your database container called `postgresql16` and is it on a common network with the planka container?

**Comment by Semias83** [comment]
My database container is called postgresql16.

In my reverse proxy network for both postgresgl container and planka container, I have the original error of my post, and the tables migration and migration_lock are created in the database.

If both containers are in bridge network type, no tables are created in the DB and I have this error:


[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
planka: https://github.com/sponsors/meltyshev

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────
Linuxserver.io version: v1.21.1-ls2
Build-date: 2024-09-12T18:26:31+00:00
───────────────────────────────────────
    
Waiting for DB postgresql16 to become available on port 5432...
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: getaddrinfo ENOTFOUND postgresql16
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'postgresql16'
}

Node.js v20.15.1
[custom-init] No custom files found, skipping...

**Comment by thespad** [comment]
That error is a DNS lookup failure, which means your planka container cannot resolve the database container using that name. Any custom compose network should handle DNS correctly, so this is assuming you're not using the actual default Bridge network (which doesn't support ICC) or macvlan/ipvlan, which we don't support and are never* a good idea.

**Comment by Semias83** [comment]
If I put my DB and Planka containers both in my reverse proxy network, and I type my DB container name (postgresql16) at DATABASE_URL, my logs are like my first message (tables migration and migration_lock are created in the DB):


/etc/s6-overlay/s6-rc.d/init-planka-config/run: line 28:   143 Illegal instruction     s6-setuidgid abc node db/init.js
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
planka: https://github.com/sponsors/meltyshev

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────
Linuxserver.io version: v1.22.0-ls3
Build-date: 2024-09-16T20:03:31+00:00
───────────────────────────────────────
    
Waiting for DB postgresql16 to become available on port 5432...
[custom-init] No custom files found, skipping...

**Comment by Semias83** [comment]
For information, I tried to make my postgresql container name the same as in the planka template (planka-db).
The result is the same error in the logs: /etc/s6-overlay/s6-rc.d/init-planka-config/run: line 28: 143 Illegal instruction s6-setuidgid abc node db/init.js

If the postegresql container is off, this error disapears and I have this one: 
Waiting for DB planka-db to become available on port 5432...
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: getaddrinfo ENOTFOUND planka-db
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'planka-db'
}

Node.js v20.15.1
[custom-init] No custom files found, skipping...

I run Version 1.23.0-ls7

**Comment by thespad** [comment]
I think this has to be something specific to your environment. I don't have an Unraid host to test with but I've tried to replicate this on multiple different docker hosts and nothing I try results in that error message.

Are you running on some 10 year old CPU or something?

**Comment by Semias83** [comment]
If it can be a problem, maybe it's my problem. I'm running on an Intel Q6600 from 2007. All of my containers works great so I didn't know that it can be a problem. The version of Planka previously on Unraid a few years ago before being removed from apps  worked great so I haven't thought of this kind of problem. 
Thanks for your time.

**Comment by thespad** [comment]
Best I can tell from the limited information available it's something that the db init script is trying to do and can't because your CPU lacks the features required, hence the illegal operation/segfault that you're seeing. You could report it upstream, but there may not be anything they can really do with a CPU that old.
