### ISSUE TITLE
Can't login with default user

### ISSUE THREAD

**Issue by jakaerc** [linuxserver/docker-planka#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When frst time on login page after install I can't login with demo@demo.demo.

### Expected Behavior

I should login with user: demo@demo.demo and pass: demo

### Steps To Reproduce

/

### Environment

```markdown
- OS: UNRAID
```

### CPU architecture

x86-64

### Docker creation

```bash
linuxserver unraid app
```

### Container logs

```bash
text  error  warn  system  array  login  

Connection to localhost (127.0.0.1) 1337 port [tcp/*] succeeded!
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
planka: https://github.com/sponsors/meltyshev

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────
Linuxserver.io version: v1.22.0-ls3
Build-date: 2024-09-16T20:03:31+00:00
───────────────────────────────────────
    
Waiting for DB 13.8.92.27 to become available on port 5432...
[custom-init] No custom files found, skipping...
[ls.io-init] done.
2024-09-17 15:21:41 [W] Invalid email or username: "demo@demo.demo"! (IP: 89.21190)
```

**Comment by thespad** [comment]
Looks like at some point upstream changed the default user so that it doesn't actually insert the user into the database unless you...set the default user to the default value. Linked PR should fix it.

**Comment by jakaerc** [comment]
I'm new to this. How do I implement the fix? Thank you.

**Comment by thespad** [comment]
Just wait until we've merged the PR and then pull the latest image.

**Comment by jakaerc** [comment]
This now works but with every reset it readds the demo@demo.demo user again and you can't delete it.

**Comment by thespad** [comment]
Well that's not great design. I'll have a look and see if I can find a way to not reinsert the user on subsequent runs, otherwise I'll have to change the setup process to work around it.

**Comment by thespad** [comment]
@jakaerc please can you test `ghcr.io/linuxserver/lspipepr-planka:v1.22.0-pkg-07fc2934-dev-51c866446b5244a1d8c6fc29e6bfffb3b32f4896-pr-6`

Please note you now need to set these envs (to whatever you want)
```
      - DEFAULT_ADMIN_EMAIL=demo@demo.demo
      - DEFAULT_ADMIN_PASSWORD=demo
      - DEFAULT_ADMIN_NAME=Demo User
      - DEFAULT_ADMIN_USERNAME=demo
```
They can be removed after the first run if you choose.

**Comment by jakaerc** [comment]
This seems to be working now as I was able to delete the demo user but not sure if I would know where to input the envs on fresh install as I'm doing it over unraid. Would there be an input field in the unraid template?

**Comment by thespad** [comment]
There will be once the PR is merged and the templates update
