### ISSUE TITLE
[BUG] Planka requires TZ=UTC

### ISSUE THREAD

**Issue by Richardk2n** [linuxserver/docker-planka#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Times in Planka are wrong if TZ=UTC is not set (see https://github.com/plankanban/planka/issues/253 https://github.com/plankanban/planka/issues/170)
They are wrong by the difference between UTC and TZ.
Therefore, TZ=UTC should be enforced in the unraid template.

### Steps To Reproduce

Install Planka on unraid from community apps, which TZ not UTC.
Add a deadline to a card.

### Environment

```markdown
- OS: Unraid 6.12.9
- How docker service was installed: Community Apps
```

### CPU architecture

x86-64

### Docker creation

```bash
Default parameters.
Notably TZ defaults to Berlin for me without input.
```

### Container logs

```bash
Not relevant.
```

**Comment by thespad** [comment]
This is terrible design and not how you handle DB datetimes, but regardless I'll see what I can do.
